DROP TABLE IF EXISTS B2C_PRDCT;
DROP TABLE IF EXISTS B2C_BRND;
DROP TABLE IF EXISTS B2C_CLR;
DROP TABLE IF EXISTS B2C_PRDCT_CTGR;
  
CREATE TABLE B2C_BRND (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL
);

  
CREATE TABLE B2C_CLR (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  CODE VARCHAR(5) NOT NULL
);

  
CREATE TABLE B2C_PRDCT_CTGR (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL
);

  
CREATE TABLE B2C_PRDCT(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  QUANTITY INT NOT NULL,
  SIZE VARCHAR(5) NOT NULL,
  PRICE INT NOT NULL,
  BRND_ID INT NOT NULL,
  foreign key (BRND_ID) references B2C_BRND(ID),
  CLR_ID INT NOT NULL,
  foreign key (CLR_ID) references B2C_CLR(ID),
  PRDCT_CTGR_ID INT NOT NULL,
  foreign key (PRDCT_CTGR_ID) references B2C_PRDCT_CTGR(ID)
);